site:
  title: 阿菇的小站
  author: ma5hr00m
  copyright: ©2023 Ma5hr00m. All rights reserved.

friends:
  -
    id: ma5hr00m
    image: https://thirdqq.qlogo.cn/g?b=sdk&k=txyQxibMaHgibdibIoacKyWJg&kti=ZI090wAAAAA&s=640
    url: http://ma5hr00m.top
  -
    id: ripple
    image: https://thirdqq.qlogo.cn/g?b=sdk&k=b5oJsh1V04z7EttTsCaqOg&kti=ZI090wAAAAE&s=640
    url: https://rippleqaq.github.io/